services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USER_NAME: bukumasjid
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql_host
      - DB_PORT=3306
      - DB_DATABASE=homestead
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
    env_file:
      - .env
    networks:
      - web-dev
    volumes:
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./storage:/var/www/html/storage
    command: ["/bin/sh", "-c", "php artisan serve --host=0.0.0.0 --port=8000"]

  mysql:
    hostname: mysql_host
    restart: unless-stopped
    platform: linux/x86_64
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - database:/var/lib/mysql
    networks:
      - web-dev

networks:
  web-dev:

volumes:
  database:
